### ISSUE TITLE
error number -1728

### ISSUE THREAD

**Issue by PedroCavaleiro** [invntiv/-Oh-My-Zsh-Apple-Music-Now-Playing-Titlebar-#1]
Hi, while playing music from Apple Music I get the error -1728, if I play from the library everything works fine even if it's streaming from Apple Music

![Screenshot 2020-11-06 at 01 24 25](https://user-images.githubusercontent.com/1993871/98314943-f4758a80-1fce-11eb-8d98-5cac325679e0.png)

**Comment by 0xVe1L** [comment]
That's interesting. Let me look into it - Thanks for logging this bug

**Comment by PedroCavaleiro** [comment]
> That's interesting. Let me look into it - Thanks for logging this bug

I found out that's probably connected to Apple Music, when I play music from my library everything works as expected

So it's like this,
If you added your local files onto your Music app it works
If you added from Apple Music onto your Music Library AND play from the library it also works
If you play directly from Apple Music (even if said music is in your library) it doesn't work

So far I was unable to find a way to make it work with this script

**Comment by PedroCavaleiro** [comment]
It was fixed by Apple in macOS 11.3, closing issue
